blog/urls.py
from django.conf.urls.defaults import *
from mysite.blog.views import archive

urlpatterns = patterns('',
	url(r'^$', archive)
	)

photo/urls.py
from django.conf.urls.defaults import *
from mysite.photo.models import Item, Photo

urlpatterns = patterns('django.views.generic',
    url(r'^$', 'simple.direct_to_template',
    kwargs = {
        'template':'index.html',
        'extra_context':{'item_list':lambda:Item.objects.all()}
    },
    name='index'
    ),
    url(r'^items/$', 'list_detail.object_list',
    kwargs={
        'queryset':Item.objects.all(),
        'template_name':'items_list.html',
        'allow_empty':True
    },
    name = 'item_list'
    ),
    
    )

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'^blog/', include('mysite.blog.urls')),

    url(r'^photo/', include('mysite.photo.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib import admin

# Create your models here.
class BlogPost(models.Model):
    # TODO: Defne fields here
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField()

    class Meta:
        ordering = ('-timestamp',)
    #     verbose_name = _('BlogPost')
    #     verbose_name_plural = _('BlogPosts')

    # def __unicode__(self):
    #     pass
    
    # def save(self):
    #     pass
    
    # def get_absolute_url(self):
    #     pass
    
    # TODO: Defne custom methods here

class BlogPostAdmin(admin.ModelAdmin):
    list_display = ('title', 'timestamp')

admin.site.register(BlogPost, BlogPostAdmin)    

class Author(models.Model):
    name = models.CharField(max_length=100)

class Book(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    num_pages = models.IntegerField()
    authors = models.ManyToManyField(Author)

    def __unicode__(self):
        return self.title

    # class Meta:
        # abstract = True

#django.core.exceptions.FieldError: Local field 'authors' in class 'SimthBook' 
#clashes with field of similar name from base class 'Book'
# class SimthBook(Book):
    # authors = models.ManyToManyField(Author,limit_choices_to={
        # 'name__endswith':'Smith' })

class Person(models.Model):
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)
    middle = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['last','first','middle']
        unique_together = ['first','last','middle']
        verbose_name_plural = 'people'

class PersonAdmin(admin.ModelAdmin):
    list_display = ('first', 'last', 'middle')

admin.site.register(Person, PersonAdmin)
        

photo/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib import admin
from mysite.utils.fields import ThumbnailImageField
 
# Create your models here.

class Item(models.Model):
  name = models.CharField(max_length=250)
  description = models.TextField()

  class Meta:
    ordering = ['name']

  def __unicode__(self):
    return self.name

  @models.permalink
  def get_absolute_url(self):
    return ('item_detail', None, {'object_id': self.id})

class Photo(models.Model):
  item = models.ForeignKey(Item)
  title = models.CharField(max_length=100)
  #image = models.ImageField(upload_to='photos')
  image = ThumbnailImageField(upload_to='photos')
  caption = models.CharField(max_length=200, blank=True)

  class Meta:
    ordering = ['title']

  def __unicode__(self):
    return self.title

  @models.permalink
  def get_absolute_url(self):
    return ('photo_detail', None, {'object_id': self.id})

class PhotoInline(admin.StackedInline):
  model = Photo

class ItemAdmin(admin.ModelAdmin):
  inlines = [PhotoInline]

admin.site.register(Item, ItemAdmin)
admin.site.register(Photo)

class oo(object):
  """docstring for oo"""
  def __init__(self, arg):
    super(oo, self).__init__()
    self.arg = arg

class ClassName(object):
  """docstring for ClassName"""
  def __init__(self, arg):
    super(ClassName, self).__init__()
    self.arg = arg
    

blog/views.py
# -*- coding: utf-8 -*-
# Create your views here.

from django.template import loader, Context
from django.http import HttpResponse
from mysite.blog.models import BlogPost

def archive(request):
	posts = BlogPost.objects.all()
	t = loader.get_template("archive.html")
	c = Context({'posts':posts})
	return HttpResponse(t.render(c))
	
from mysite.blog.models import Book
from datetime import datetime
#from somewhere import some_function_returing_a_queryset
from django.db.models import Q

def q(request):
	book_queryset = some_function_returing_a_queryset()
	today = datetime.now()
	overdue_books = book_queryset.filter(due_date__lt=today)
	
	#Q
	specific_does = Person.objects.filter(last="Doe").exclude(
		Q(first="John") | Q(middle="Quincy")
	)
	
	# grabs all the Does, named John Smith,but not any one named John W.Smith
	other_does = Person.objects.filter(Q(last="Doe") | 
		(Q(last="Smith") & Q(first="John") & ~Q(middle__startswith="W"))
		)

from django.db import connection

def queryo():
	cursor = connection.cursor()
	cursor.execute("select * from blog_person")
	doe_rows = cursor.fetchall()
	for row in doe_rows:
		print "%S %s" % (row[0], row[1])

photo/views.py
# Create your views here.

blog/templates/archive.html
{% extends "base.html" %}
{% block content %}
{% for post in posts %}
<h2>{{ post.title}}</h2>
<p>{{ post.timestamp }}</p>
<p>{{ post.body }}</p>
{% endfor %}
{% endblock %}

blog/templates/base.html
<html>
<style type="text/css">
body{ color: #efd; background-color: #453; padding: 0 5em; margin: 0}
h1{ padding: 2em 1em; background: #675;}
h2{ color: #bf8; border-top: 1px dotted #fff; margin-tip: 2em;}
p{ margin: 1em 0;}
</style>

<head>
	<title></title>
</head>
<body>
<h1>mysite.example.com</h1>
{% block content %}
{% endblock%}
</body>
</html>

photo/templates/base.html
<html>
    <head>
    <title>Galley - {% block title%} {% endblock%}</title>
    <style type="text/css">
        border {margin:30px, font-family:sans-serif; background-color: #fff;}
        h1 {background: #ccf; padding: 20px;}
        h2 {background: #ddf; padding: 10px 20px;}
        h3 {background: #eef; padding: 5px 20px;}
        table {width: 100%;}
        table th {text-align:left;}
    </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

photo/templates/base2.html
<html>

    <head>
    <title>Galley - {% block title%} {% endblock%}</title>
    <style type="text/css">
        border {margin:30px, font-family:sans-serif; background-color: #fff;}
        h1 {background: #ccf; padding: 20px;}
        h2 {background: #ddf; padding: 10px 20px;}
        h3 {background: #eef; padding: 5px 20px;}
        table {width: 100%;}
        table th {text-align:left;}
    </style>
    </head>
    <body>
        <h1>Gallery</h1>
        {% block content %}{% endblock %}
    </body>
</html>

photo/templates/index.html
{% extends "base2.html" %}

{%block title%}Home{% endblock %}
{% block content %}

<h2>Welcome to the Gallery!</h2>
<p>Heare you find pictures of various items, Below are some highlighted itmes;use the link at the bottom to see the full listing.</p>

<h3>Showcase</h3>
<table>
<tr>
    {% for item in item_list|slice:':3' %}
    <td>
        <a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br />
        {% if item.photo_set.count %}
            <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
        {% else %}
            <span>No photos (yet)</span>
        {% endif %}
        </a>
    </td>
    {% endfor %}
</tr>
</table>
<p><a href="{% url item_list %}">View the full list &rquuo;</a></p>

{% endblock %}